---
title: "W241 Final - Tipping Project"
author: "Ben Attix, Chris Beecroft, Matt Burke, Brock Kowalchuk"
date: "4/23/2017"
output: pdf_document
---

```{r setup, include=FALSE}
setwd("~/Desktop/w241-Final-Project/")
library(foreign)
library(data.table)
library(AER)
library(stargazer)
library(DataCombine)
library(lmtest)
library(sandwich)
library(lattice)
library(psych)
```

```{r}
# READING IN DATA & COUNTS
df = read.csv("DataforAnalysis2.csv")

# DON'T NEED CUTOFF DATE ANYMORE - WAS HANDLED BEFORE DATASET WAS LOADED
  # set earliest date of acceptable data
  #cutoff_date = strftime("2017-04-03 0:0:0", "%Y-%m-%d %H:%M:%S")
  #remove all data before cutoff date
  #df = df[strptime(df$StartDate, "%Y-%m-%d %H:%M:%S") > cutoff_date, ]

# counts for control and treatment groups
n.control = length(df$total_tip[df$total_tip > 0])
n.treatment = length(df$total_no_tip[df$total_no_tip > 0])
```
# Transformations

### Price
```{r}
# Total price
df$total_all = ifelse(df$total_no_tip == 0, df$total_tip, df$total_no_tip)

names(df)[names(df) == "Q23"] = "tip" 

# Caculate pre-tip total price for the tipping group
df$total_pre_tip = df$total_tip - df$tip  
df$tip_pct = (df$tip / df$total_pre_tip) * 100
```

### Create new variables which contains values for both treatment and control
```{r}
# Q7 and Q31 - Meals
df$meal_ordered = ifelse(df$Q7 == "", df$Q31, df$Q7)
levels(df$meal_ordered) = levels(df$Q7)

# Q16 and Q30 - Beverages
df$drink_ordered = ifelse(df$Q16 == "", df$Q30, df$Q16)
levels(df$drink_ordered) = levels(df$Q16)

# Q8 and Q35 - Reasonable Score
df$reasonable = ifelse(df$Q8 == "", df$Q35, df$Q8)

# recode so that 1=Extremely unreasonable and 5=Extremely reasonable
## it is originally ordered alphabetically
df$reasonable = recode(df$reasonable, "2=5; 3=1; 4=3; 5=4; 6=2")
levels(df$reasonable) = c("Extremely unreasonable",
                          "Somewhat unreasonable",
                          "Neither reasonable nor unreasonable",
                          "Somewhat reasonable",
                          "Extremely reasonable")
```

### Treatment Flag Plus Renaming
```{r}
# Treatment flag
df$treat = ifelse(df$total_no_tip > 0, 1, 0)
levels(df$treat) = c("Tipping", "Fixed-Pricing")

# Rename some variables
names(df)[names(df) == "Q23.1"] = "gender" 
names(df)[names(df) == "Q24"] = "age" 
names(df)[names(df) == "Q5"] = "baseline_spend" 
names(df)[names(df) == "Q26"] = "baseline_tip_pct"
names(df)[names(df) == "Q1_1"] = "baseline_eat_out" 
```

### Dummy Variables
```{r}
# Q2
df$Q2_family = ifelse(grepl("Family", df$Q2, ignore.case = T), 1, 0)
df$Q2_friends = ifelse(grepl("Friends", df$Q2, ignore.case = T), 1, 0)
df$Q2_alone = ifelse(grepl("alone", df$Q2, ignore.case = T), 1, 0)
df$Q2_spouse = ifelse(grepl("Spouse", df$Q2, ignore.case = T), 1, 0)
df$Q2_colleague = ifelse(grepl("Colleagues", df$Q2, ignore.case = T), 1, 0)

# Q3
df$Q3_mainCourse = ifelse(grepl("Main", df$Q3, ignore.case = T), 1, 0)
df$Q3_appetizer = ifelse(grepl("Appetizer", df$Q3, ignore.case = T), 1, 0)
df$Q3_dessert = ifelse(grepl("Dessert", df$Q3, ignore.case = T), 1, 0)

# Q4
df$Q4_water = ifelse(grepl("Water", df$Q4, ignore.case = T), 1, 0)
df$Q4_non_alc = ifelse(grepl("beverages", df$Q4, ignore.case = T), 1, 0)
df$Q4_beer = ifelse(grepl("beer", df$Q4, ignore.case = T), 1, 0)
df$Q4_cocktail = ifelse(grepl("Cocktail", df$Q4, ignore.case = T), 1, 0)
df$Q4_wine = ifelse(grepl("Wine", df$Q4, ignore.case = T), 1, 0)

# Meal Ordered
df$meal_duck = ifelse(df$meal_ordered == 2, 1, 0)
df$meal_fettuccine = ifelse(df$meal_ordered == 3, 1, 0)
df$meal_fish = ifelse(df$meal_ordered == 4, 1, 0)
df$meal_pizza = ifelse(df$meal_ordered == 5, 1, 0)
df$meal_pork = ifelse(df$meal_ordered == 6, 1, 0)

# Drink ordered
df$drink_water = ifelse(df$meal_ordered == 2, 1, 0)
df$drink_craftbeer = ifelse(df$meal_ordered == 3, 1, 0)
df$drink_macrobeer = ifelse(df$meal_ordered == 4, 1, 0)
df$drink_wine = ifelse(df$meal_ordered == 5, 1, 0)
df$drink_cocktail = ifelse(df$meal_ordered == 6, 1, 0)
```


# EDA
```{r}
# Average price per treatment group
mean(df$total_all[df$treat==1])
mean(df$total_all[df$treat==0])
```


```{r}
# Hisograms of Reasonable Score
histogram(~ reasonable | levels(treat), data = df, 
          xlab = "Rating (1=Very Unreasonable to 5=Very Reasonable)",
          main = "Feelings About Meal Cost" )
```


```{r}
hist(df$tip, main = "Tip Amount", xlab = "Dollars", breaks=10)
```

```{r}
plot(df$tip, df$total_pre_tip)
```

```{r}
scatter.hist(df$tip, df$total_pre_tip, title = "Tip Amount vs Pre-Tip Meal Cost", xlab = "Tip (in $)", ylab = "Pre-Tip Meal Cost (in $)")
```


```{r}
# Naive model
model_naive = lm(reasonable ~ treat, data = df)
summary(model_naive)
```


```{r}
# Control for demographics
model2 = lm(reasonable ~ treat + factor(gender) + factor(age), data = df)
summary(model2)
```


```{r}
# Control for eating baseline dining habits
model3 = lm(reasonable ~ treat + Q2_colleague + Q2_spouse + Q2_alone + Q2_friends + Q2_family + Q3_dessert + Q3_appetizer + Q3_mainCourse + Q4_wine + Q4_cocktail + Q4_beer + Q4_non_alc + Q4_water + baseline_tip_pct + baseline_spend + baseline_eat_out, data = df)
summary(model3)
```


```{r}
# Control for price
model4 = lm(reasonable ~ treat + total_all, data = df)
summary(model4)
```

```{r}
# Control for price and order
model5 = lm(reasonable ~ treat + total_all + factor(meal_ordered) + factor(drink_ordered), data = df)
summary(model5)
```

```{r}
model6 = lm(reasonable ~ treat + baseline_tip_pct, data = df)
summary(model6)
```

